import { Model } from "../React/Model-library/model-library";

export const dummyModels: Model[] = [
    {
        name: "Model 1",
        type: "India",
        llm: "Asia",
        description: "Description of Model 1",
        createdOn: "2024-01-01",
        lastTrainedOn: "2024-01-10",
        status: "Active",
    },
    {
        name: "Model 2",
        type: "India",
        llm: "Asia",
        description: "Description of Model 2",
        createdOn: "2024-02-02",
        lastTrainedOn: "2024-02-12",
        status: "Active",
    },
    {
        name: "Model 3",
        type: "India",
        llm: "Asia",
        description: "Description of Model 3",
        createdOn: "2024-03-03",
        lastTrainedOn: "2024-03-10",
        status: "Active",
    },
    {
        name: "Model 4",
        type: "India",
        llm: "Asia",
        description: "Description of Model 4",
        createdOn: "2024-04-04",
        lastTrainedOn: "2024-04-10",
        status: "Active",
    },
    {
        name: "Model 5",
        type: "India",
        llm: "Asia",
        description: "Description of Model 5",
        createdOn: "2024-05-05",
        lastTrainedOn: "2024-05-10",
        status: "Active",
    },
    {
        name: "Model 6",
        type: "India",
        llm: "Asia",
        description: "Description of Model 6",
        createdOn: "2024-06-06",
        lastTrainedOn: "2024-06-10",
        status: "Active",
    },
    {
        name: "Model 7",
        type: "India",
        llm: "Asia",
        description: "Description of Model 7",
        createdOn: "2024-07-07",
        lastTrainedOn: "2024-07-10",
        status: "Active",
    },
    {
        name: "Model 8",
        type: "India",
        llm: "Asia",
        description: "Description of Model 8",
        createdOn: "2024-08-08",
        lastTrainedOn: "2024-08-10",
        status: "Active",
    },
    {
        name: "Model 9",
        type: "India",
        llm: "Asia",
        description: "Description of Model 9",
        createdOn: "2024-09-09",
        lastTrainedOn: "2024-09-10",
        status: "Active",
    },
    {
        name: "Model 10",
        type: "India",
        llm: "Asia",
        description: "Description of Model 10",
        createdOn: "2024-10-10",
        lastTrainedOn: "2024-10-10",
        status: "Active",
    },
    {
        name: "Model 11",
        type: "India",
        llm: "Asia",
        description: "Description of Model 11",
        createdOn: "2024-11-11",
        lastTrainedOn: "2024-11-15",
        status: "Active",
    },
    {
        name: "Model 12",
        type: "India",
        llm: "Asia",
        description: "Description of Model 12",
        createdOn: "2024-12-12",
        lastTrainedOn: "2024-12-15",
        status: "Active",
    },
    {
        name: "Model 13",
        type: "India",
        llm: "Asia",
        description: "Description of Model 13",
        createdOn: "2025-01-01",
        lastTrainedOn: "2025-01-10",
        status: "Active",
    },
    {
        name: "Model 14",
        type: "India",
        llm: "Asia",
        description: "Description of Model 14",
        createdOn: "2025-02-02",
        lastTrainedOn: "2025-02-10",
        status: "Active",
    },
    {
        name: "Model 15",
        type: "India",
        llm: "Asia",
        description: "Description of Model 15",
        createdOn: "2025-03-03",
        lastTrainedOn: "2025-03-10",
        status: "Active",
    },
    {
        name: "Model 16",
        type: "India",
        llm: "Asia",
        description: "Description of Model 16",
        createdOn: "2025-04-04",
        lastTrainedOn: "2025-04-10",
        status: "Active",
    },
    {
        name: "Model 17",
        type: "India",
        llm: "Asia",
        description: "Description of Model 17",
        createdOn: "2025-05-05",
        lastTrainedOn: "2025-05-10",
        status: "Active",
    },
    {
        name: "Model 18",
        type: "India",
        llm: "Asia",
        description: "Description of Model 18",
        createdOn: "2025-06-06",
        lastTrainedOn: "2025-06-10",
        status: "Active",
    },
    {
        name: "Model 19",
        type: "India",
        llm: "Asia",
        description: "Description of Model 19",
        createdOn: "2025-07-07",
        lastTrainedOn: "2025-07-10",
        status: "Active",
    },
    {
        name: "Model 20",
        type: "India",
        llm: "Asia",
        description: "Description of Model 20",
        createdOn: "2025-08-08",
        lastTrainedOn: "2025-08-10",
        status: "Active",
    },
    {
        name: "Model 21",
        type: "India",
        llm: "Asia",
        description: "Description of Model 21",
        createdOn: "2025-09-09",
        lastTrainedOn: "2025-09-10",
        status: "Active",
    },
    {
        name: "Model 22",
        type: "India",
        llm: "Asia",
        description: "Description of Model 22",
        createdOn: "2025-10-10",
        lastTrainedOn: "2025-10-10",
        status: "Active",
    },
    {
        name: "Model 23",
        type: "India",
        llm: "Asia",
        description: "Description of Model 23",
        createdOn: "2025-11-11",
        lastTrainedOn: "2025-11-15",
        status: "Active",
    },
    {
        name: "Model 24",
        type: "India",
        llm: "Asia",
        description: "Description of Model 24",
        createdOn: "2025-12-12",
        lastTrainedOn: "2025-12-15",
        status: "Active",
    },
    {
        name: "Model 25",
        type: "India",
        llm: "Asia",
        description: "Description of Model 25",
        createdOn: "2026-01-01",
        lastTrainedOn: "2026-01-10",
        status: "Active",
    },
    {
        name: "Model 26",
        type: "India",
        llm: "Asia",
        description: "Description of Model 26",
        createdOn: "2026-02-02",
        lastTrainedOn: "2026-02-10",
        status: "Active",
    },
    {
        name: "Model 27",
        type: "India",
        llm: "Asia",
        description: "Description of Model 27",
        createdOn: "2026-03-03",
        lastTrainedOn: "2026-03-10",
        status: "Active",
    },
    {
        name: "Model 28",
        type: "India",
        llm: "Asia",
        description: "Description of Model 28",
        createdOn: "2026-04-04",
        lastTrainedOn: "2026-04-10",
        status: "Active",
    },
    {
        name: "Model 29",
        type: "India",
        llm: "Asia",
        description: "Description of Model 29",
        createdOn: "2026-05-05",
        lastTrainedOn: "2026-05-10",
        status: "Active",
    },
    {
        name: "Model 30",
        type: "India",
        llm: "Asia",
        description: "Description of Model 30",
        createdOn: "2026-06-06",
        lastTrainedOn: "2026-06-10",
        status: "Active",
    },
    {
        name: "Model 31",
        type: "India",
        llm: "Asia",
        description: "Description of Model 31",
        createdOn: "2026-07-07",
        lastTrainedOn: "2026-07-10",
        status: "Active",
    },
    {
        name: "Model 32",
        type: "India",
        llm: "Asia",
        description: "Description of Model 32",
        createdOn: "2026-08-08",
        lastTrainedOn: "2026-08-10",
        status: "Active",
    },
    {
        name: "Model 33",
        type: "India",
        llm: "Asia",
        description: "Description of Model 33",
        createdOn: "2026-09-09",
        lastTrainedOn: "2026-09-10",
        status: "Active",
    },
    {
        name: "Model 34",
        type: "India",
        llm: "Asia",
        description: "Description of Model 34",
        createdOn: "2026-10-10",
        lastTrainedOn: "2026-10-10",
        status: "Active",
    },
];
